language: python
python:
  - "3.6"
script:
  - ./archiver.sh
after_success:
  - ./add_existing_files.sh
deploy:
  provider: pages
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set as an environment variable in the Travis settings for this repo
  keep-history: true
  local-dir: docs
  on:
    branch: master
